<a href="https://colab.research.google.com/github/Akash7791/ML/blob/master/Classification_Combine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [ ]:
X = sc.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

# **Logistic Regression**

In [7]:
from sklearn.linear_model import LogisticRegression
logistic_regressor = LogisticRegression(random_state=0)

In [8]:
logistic_regressor.fit(X_train, y_train)
y_pred = logistic_regressor.predict(X_test)

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred)
accuracy_score(y_test, y_pred)

0.9473684210526315

# **KNN**

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
knn_classifier = KNeighborsClassifier(n_neighbors=5, weights='uniform', metric='minkowski', p=2)
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [14]:
y_pred = knn_classifier.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)

[[103   4]
 [  5  59]]


0.9473684210526315

# **SVM**

In [17]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel='linear',random_state=0)

In [18]:
svm_classifier.fit(X_train, y_train)
y_pred = svm_classifier.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)

[[102   5]
 [  5  59]]


0.9415204678362573

# **Kernel SVM**

In [20]:
from sklearn.svm import SVC
kernel_svm_classifier = SVC(kernel='rbf',random_state=0)

In [21]:
kernel_svm_classifier.fit(X_train, y_train)
y_pred = kernel_svm_classifier.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)

[[102   5]
 [  3  61]]


0.9532163742690059

# **Naive Bayes**

In [24]:
from sklearn.naive_bayes import GaussianNB
bayes_classifier = GaussianNB()

In [25]:
bayes_classifier.fit(X_train, y_train)
y_pred = bayes_classifier.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)

[[99  8]
 [ 2 62]]


0.9415204678362573

# **Decision Tree**

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
tree_classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)
tree_classifier.fit(X_train, y_train)
y_pred = tree_classifier.predict(X_test)

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)

[[103   4]
 [  3  61]]


0.9590643274853801

# **Random Forest**

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
random_forest_classifier = RandomForestClassifier(n_estimators=100, criterion='entropy',random_state=0)
random_forest_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [33]:
y_pred = random_forest_classifier.predict(X_test)

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)

[[103   4]
 [  5  59]]


0.9473684210526315