<a href="https://colab.research.google.com/github/Akash7791/ML/blob/master/Regression_Combine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [0]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# **Multiple Linear Regression**

In [0]:
from sklearn.linear_model import LinearRegression
linear_regressor = LinearRegression()
linear_regressor.fit(X_train, y_train)
ypred_linear = linear_regressor.predict(X_test)

In [0]:
np.set_printoptions(precision=2)

In [14]:
print(np.concatenate((ypred_linear.reshape(len(ypred_linear),1), y_test.reshape(len(y_test),1)), 1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


In [15]:
from sklearn.metrics import r2_score
r2_score(y_test, ypred_linear)

0.9325315554761302

# **Polynomial Regression**

In [0]:
from sklearn.preprocessing import PolynomialFeatures

In [0]:
polynomialregressor = PolynomialFeatures(degree=4)

In [18]:
X_poly = polynomialregressor.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
ypred_poly = regressor.predict(polynomialregressor.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((ypred_poly.reshape(len(ypred_poly),1), y_test.reshape(len(y_test),1)) ,1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


In [25]:
r2_score(ypred_poly, y_test)

0.9425115817622165

# **Support Vector Regression**

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()

In [0]:
X_train_svr = sc_X.fit_transform(X_train)

In [0]:
y_train_reshaped = y_train.reshape(len(y_train),1)
y_train_svr = sc_y.fit_transform(y_train_reshaped)

In [0]:
from sklearn.svm import SVR

In [38]:
svr = SVR(kernel='rbf')
svr.fit(X_train_svr, y_train_svr)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
ypred_svr = sc_y.inverse_transform(svr.predict(sc_X.transform(X_test)))

In [42]:
np.set_printoptions(precision=2)
print(np.concatenate((ypred_svr.reshape(len(ypred_svr),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


In [43]:
r2_score(ypred_svr, y_test)

0.9462379188596809

# **Decision Tree Regression**

In [0]:
from sklearn.tree import DecisionTreeRegressor

In [45]:
decisiontreeregressor = DecisionTreeRegressor(random_state=0)
decisiontreeregressor.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [0]:
ypred_decisiontree = decisiontreeregressor.predict(X_test)

In [48]:
np.set_printoptions(precision=2)
print(np.concatenate((ypred_decisiontree.reshape(len(ypred_decisiontree),1), y_test.reshape(len(y_test),1)),1))

[[431.28 431.23]
 [462.81 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.55 463.28]]


In [49]:
r2_score(ypred_decisiontree, y_test)

0.9212071233241356

# **Random Forest**

In [0]:
from sklearn.ensemble import RandomForestRegressor

In [0]:
randomforest = RandomForestRegressor(n_estimators=10, random_state=0)

In [0]:
randomforest.fit(X_train, y_train)
ypred_random = randomforest.predict(X_test)

In [53]:
np.set_printoptions(precision=2)
print(np.concatenate((ypred_random.reshape(len(ypred_random),1), y_test.reshape(len(y_test),1)),1))

[[433.78 431.23]
 [457.99 460.01]
 [463.14 461.14]
 ...
 [470.16 473.26]
 [439.51 438.  ]
 [460.32 463.28]]


In [54]:
r2_score(ypred_random, y_test)

0.9599654651764917